### Register
POST http://localhost:2333/register
Content-Type: application/json

{
  "email": "lajizr@sssser.com",
  "nickname": "ass",
  "password": "b",
  "username": "ssbssssss"
}

### Create Subject
POST http://localhost:2333/subject/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEzLCJnaWQiOjEsImV4cCI6MTY4NzI4NzA5MX0.hMkbN70ttP5mRlmJ8U4rrK9z96JrkIE1kmw4zJwCX1I
Content-Type: application/json

{
  "name": "Comic girlsssss",
  "name_cn": "动漫女孩",
  "image": "http://www.csdn.com",
  "year" : 2023,
  "month" : 12,
  "date"  : 1,
  "summary": "非常非常非常非常非常好看",
  "episodes": 20,
  "weekDay": 5
}

### Login
POST http://localhost:2333/login
Content-Type: application/json

{
  "email": "lajizr@sssser.com",
  "password": "b"
}

### Cancel
POST http://localhost:2333/cancel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2LCJnaWQiOjAsImV4cCI6MTY4NzI2MDYyMn0.22mhLSniGYNBImhso94en2jSTImtsm1RJpkhuIP97XQ

### GET subject
GET http://localhost:2333/subject/get
Content-Type: application/json

### GET subject by ID
GET http://localhost:2333/subject/2/sdfasdf
Content-Type: application/json

### collection
POST http://localhost:2333/subject_collection/add/2/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjMsImdpZCI6MSwiZXhwIjoxNjg3MzY0MTg0fQ.LqbQqj6Hc0-HM3fND5_zemx9b7KXqi7B9raR3sT6Lqw
Content-Type: application/json


### Get Comments
GET http://localhost:2333/collection/self/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjcsImdpZCI6MCwiZXhwIjoxNjg3NjgzMDMzfQ.RwB9mTgeU2wpg4BynYbjWkfLwA7EqPeHgaL6rFyHfKg
Content-Type: application/json


### collection
PATCH http://localhost:2333/collection/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjcsImdpZCI6MCwiZXhwIjoxNjg3NjgzMDMzfQ.RwB9mTgeU2wpg4BynYbjWkfLwA7EqPeHgaL6rFyHfKg
Content-Type: application/json

{
  "comment": "非常非常非常非常非常好看ssss",
  "type": 3,
  "has_comment": true
}

###
PATCH http://localhost:2333/collection/update/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjQsImdpZCI6MCwiZXhwIjoxNjg3NDkwNDM3fQ.LHHcTywhLkEW6NNKaDU2brHvvk7ETE1mDTGjAiXIi5k
Content-Type: application/json

{
  "comment": "非常非常非常非常非常好看",
  "score": 10,
  "collectionType": 3
}

###
GET http://localhost:2333/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjcsImdpZCI6MCwiZXhwIjoxNjg3NjgzMDMzfQ.RwB9mTgeU2wpg4BynYbjWkfLwA7EqPeHgaL6rFyHfKg
Content-Type: application/json

### Get avatar
GET http://localhost:2333/user/12/dsadas
Content-Type: application/json

### Get Comments
GET http://localhost:2333/collection/7/member/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjcsImdpZCI6MCwiZXhwIjoxNjg3NjgzMDMzfQ.RwB9mTgeU2wpg4BynYbjWkfLwA7EqPeHgaL6rFyHfKg
Content-Type: application/json






