### Register
POST http://localhost:2333/register
Content-Type: application/json

{
  "email": "lajizr@er.com",
  "nickname": "ass",
  "password": "b",
  "username": "ssbsss"
}

### Create Subject
POST http://localhost:2333/subject/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEzLCJnaWQiOjEsImV4cCI6MTY4NzI4NzA5MX0.hMkbN70ttP5mRlmJ8U4rrK9z96JrkIE1kmw4zJwCX1I
Content-Type: application/json

{
  "name": "Comic girls",
  "name_cn": "动漫女孩",
  "image": "http://www.csdn.com",
  "date": "2023-06-07",
  "summary": "非常非常非常非常非常好看",
  "type": 1
}

### Login
POST http://localhost:2333/login
Content-Type: application/json

{
  "email": "lajizr@er.com",
  "password": "b"
}

### Cancel
POST http://localhost:2333/cancel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2LCJnaWQiOjAsImV4cCI6MTY4NzI2MDYyMn0.22mhLSniGYNBImhso94en2jSTImtsm1RJpkhuIP97XQ

### GET subject
GET http://localhost:2333/subject/get
Content-Type: application/json

### GET subject by ID
GET http://localhost:2333/subject/2
Content-Type: application/json

### collection
POST http://localhost:2333/subject_collection/add/2/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjMsImdpZCI6MSwiZXhwIjoxNjg3MzY0MTg0fQ.LqbQqj6Hc0-HM3fND5_zemx9b7KXqi7B9raR3sT6Lqw
Content-Type: application/json

### collection
PATCH http://localhost:2333/collection/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjMsImdpZCI6MSwiZXhwIjoxNjg3MzY0MTg0fQ.LqbQqj6Hc0-HM3fND5_zemx9b7KXqi7B9raR3sT6Lqw
Content-Type: application/json

{
  "comment": "非常非常非常非常非常好看",
  "type": 1

}

###
PATCH http://localhost:2333/collection/update/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjMsImdpZCI6MSwiZXhwIjoxNjg3MzY0MTg0fQ.LqbQqj6Hc0-HM3fND5_zemx9b7KXqi7B9raR3sT6Lqw
Content-Type: application/json

{
  "comment": "非常非常非常非常非常好看",
  "score": 10,
  "collectionType": 3

}


### Get avatar
GET http://localhost:2333/user/12/dsadas
Content-Type: application/json


