### Register
POST http://localhost:2333/register
Content-Type: application/json

{
  "email": "lajizr@sssser.com",
  "nickname": "ass",
  "password": "b",
  "username": "ssb"
}

###
GET http://localhost:2333/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImdpZCI6MSwiZXhwIjoxNjg3ODcyNzkzfQ.VE_8nGL2tX0LF4q8xACTVOrntBljcyA7ErmpF-m57no
Content-Type: application/json

### Create Subject
POST http://localhost:2333/subject/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImdpZCI6MSwiZXhwIjoxNjg3ODcyNzkzfQ.VE_8nGL2tX0LF4q8xACTVOrntBljcyA7ErmpF-m57no
Content-Type: application/json

{
  "name": "Comic girlsssss",
  "name_cn": "动漫女孩",
  "image": "http://www.csdn.com",
  "year" : 2023,
  "month" : 12,
  "date"  : 1,
  "summary": "非常非常非常非常非常好看",
  "episodes": 20,
  "weekDay": 5
}


### Login
POST http://aivwe.top/login
Content-Type: application/json

{
  "email": "1@1.com",
  "password": "114514"
}

### Cancel
POST http://localhost:2333/cancel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2LCJnaWQiOjAsImV4cCI6MTY4NzI2MDYyMn0.22mhLSniGYNBImhso94en2jSTImtsm1RJpkhuIP97XQ

### GET subject
GET http://localhost:2333/subject/get
Content-Type: application/json

### GET subject by ID
GET http://localhost:2333/subject/2
Content-Type: application/json

### collection
POST http://localhost:2333/subject_collection/add/2/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjMsImdpZCI6MSwiZXhwIjoxNjg3MzY0MTg0fQ.LqbQqj6Hc0-HM3fND5_zemx9b7KXqi7B9raR3sT6Lqw
Content-Type: application/json

### Get Comments
GET http://localhost:2333/1/subject/comment
Content-Type: application/json

### Get BoardCast
GET http://localhost:2333/board_cast/1
Content-Type: application/json

### collection
POST http://aivwe.top/collection/67
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImdpZCI6MSwiZXhwIjoxNjg4MTMyMTMxfQ.FMr-YEMZAcxAYjr1blmun5ZXN8GRphVDIhUp-tHW4OU
Content-Type: application/json

{
  "comment": "非常非常非常非常非常好看",
  "type": 5,
  "has_comment": true,
   "score": 8
}

### collection
GET http://aivwe.top/collection/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImdpZCI6MSwiZXhwIjoxNjg4MTMyMTMxfQ.FMr-YEMZAcxAYjr1blmun5ZXN8GRphVDIhUp-tHW4OU
Content-Type: application/json

###
PATCH http://localhost:2333/collection/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImdpZCI6MSwiZXhwIjoxNjg4MTMyOTg4fQ.gmXLZxkJ0y_UMbpPSAYck_NAtkcdX2sH4h2amYX3iMU
Content-Type: application/json

{
  "comment": "非常非常非常非常非常好看",
  "score": 9,
  "collectionType": 3,
  "has_comment" : true,
  "Type" : 2
}

###
GET http://localhost:2333/2/collection
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjUsImdpZCI6MCwiZXhwIjoxNjg3OTE0NTk1fQ.BAygxINh5xcEifqCwOVCaTRh48SXfDeKcLjjoP1mJ8g
Content-Type: application/json

###
GET http://localhost:2333/subject/get
Content-Type: application/json

###
GET http://localhost:2333/collection/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjUsImdpZCI6MCwiZXhwIjoxNjg3OTE0NTk1fQ.BAygxINh5xcEifqCwOVCaTRh48SXfDeKcLjjoP1mJ8g
Content-Type: application/json

###
GET http://localhost:2333/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjcsImdpZCI6MCwiZXhwIjoxNjg3NjgzMDMzfQ.RwB9mTgeU2wpg4BynYbjWkfLwA7EqPeHgaL6rFyHfKg
Content-Type: application/json

### Get avatar
GET http://localhost:2333/user/12/dsadas
Content-Type: application/json

### Get Comments
GET http://localhost:2333/7/member/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjcsImdpZCI6MCwiZXhwIjoxNjg3NjgzMDMzfQ.RwB9mTgeU2wpg4BynYbjWkfLwA7EqPeHgaL6rFyHfKg
Content-Type: application/json

### Get Comments
GET http://localhost:2333/2/subject/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjcsImdpZCI6MCwiZXhwIjoxNjg3NjgzMDMzfQ.RwB9mTgeU2wpg4BynYbjWkfLwA7EqPeHgaL6rFyHfKg
Content-Type: application/json

### Get Member
GET http://localhost:2333/user/1
Content-Type: application/json

###  Get Subject and its field
GET http://localhost:2333/subject/2
Content-Type: application/json

### Get Ranks
GET http://10.19.128.195:2333/subject/ranks
Content-Type: application/json

### Get Ranks
GET http://aivwe.top/subject/ranks
Content-Type: application/json

### Create Subject
PUT http://localhost:2333/subject/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImdpZCI6MSwiZXhwIjoxNjg3ODcyNzkzfQ.VE_8nGL2tX0LF4q8xACTVOrntBljcyA7ErmpF-m57no
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="createSubject"
Content-Type: application/json

{
  "name": "Comic girlshaha",
  "name_cn": "动漫女孩",
  "image": "http://www.csdn.com",
  "year" : 2023,
  "month" : 12,
  "date"  : 1,
  "summary": "非常非常非常非常非常好看",
  "episodes": 20,
  "weekDay": 5
}
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="ruby.jpg"

< ./image/ruby.jpg
--WebAppBoundary--

###
GET http://aivwe.top/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImdpZCI6MSwiZXhwIjoxNjg3ODcyNzkzfQ.VE_8nGL2tX0LF4q8xACTVOrntBljcyA7ErmpF-m57no
Content-Type: multipart/form-data; boundary=WebAppBoundary

### Modify information and avatar
PUT http://localhost:2333/modify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImdpZCI6MSwiZXhwIjoxNjg3ODcyNzkzfQ.VE_8nGL2tX0LF4q8xACTVOrntBljcyA7ErmpF-m57no
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="info"
Content-Type: application/json

{
    "username": "__114514",
    "nickname": "_1919810",
    "password": "1037666",
    "email": "ssesm@ssesmsmsm.com"
}
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="ruby.jpg"

< ./image/ruby.jpg
--WebAppBoundary--

###
GET http://aivwe.top/search
Content-Type: application/json

{
  "name": "th"
}


