### Register
POST http://localhost:2333/register
Content-Type: application/json

{
  "username": "_uuu111",
  "email": "9@99.com",
  "nickname": "a",
  "password": "b"
}

### Login
POST http://localhost:2333/login
Content-Type: application/json

{

  "email": "9@99.com",
  "password": "b"

}

### Cancel
POST http://localhost:2333/cancel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjksImdpZCI6MCwiZXhwIjoxNjg3MzEzMjM1fQ.ifJ-gY5O0_t73aYab0C9pwGHYpbLdeuJqM34LP3VR2w

### Get me
GET http://localhost:2333/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjksImdpZCI6MCwiZXhwIjoxNjg3MzA5NTcyfQ.sZvpb-pvsP5QNFYRRdQJKiPhO-gozWq-2RmzEH2kLzU

### Get avatar
GET http://localhost:2333/user/12/avatar
Content-Type: application/json

### Modify information and avatar
PUT http://localhost:2333/modify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE0LCJnaWQiOjAsImV4cCI6MTY4NzMxOTE5OX0.Kwd8m2YKTTtm9AItvbSrP0yrKzpjqI_xHxLaHFMh5Mg
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="info"
Content-Type: application/json

{
    "username": "__114514",
    "nickname": "_1919810",
    "password": "1037+666",
    "email": "ssesm@ssesmsmsm.com"
}
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="ruby.jpg"

< ./image/ruby.jpg
--WebAppBoundary--
