### Register
POST http://localhost:2333/register
Content-Type: application/json

{
  "username": "_uuu111",
  "email": "9@99.com",
  "nickname": "a",
  "password": "b"
}

### Login
POST http://localhost:2333/login
Content-Type: application/json

{
  "email": "9@99.com",
  "password": "b"
}

### Cancel
POST http://localhost:2333/cancel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImdpZCI6MCwiZXhwIjoxNjg3Mjg0MzM0fQ.R0LuZ7cupUNYSGFTcnkSenRt4yQgFBgu-sNkgMbVv9c

### Get me
GET http://localhost:2333/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjksImdpZCI6MCwiZXhwIjoxNjg3MzA5NTcyfQ.sZvpb-pvsP5QNFYRRdQJKiPhO-gozWq-2RmzEH2kLzU

### Get avatar
GET http://localhost:2333/user/3/avatar
Content-Type: application/json
