// Code generated by ent, DO NOT EDIT.

package subject

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the subject type in the database.
	Label = "subject"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "uid"
	// FieldImage holds the string denoting the image field in the database.
	FieldImage = "image"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"
	// FieldNameCn holds the string denoting the name_cn field in the database.
	FieldNameCn = "name_cn"
	// FieldOnHold holds the string denoting the on_hold field in the database.
	FieldOnHold = "on_hold"
	// FieldWish holds the string denoting the wish field in the database.
	FieldWish = "wish"
	// FieldDoing holds the string denoting the doing field in the database.
	FieldDoing = "doing"
	// FieldSubjectType holds the string denoting the subject_type field in the database.
	FieldSubjectType = "subject_type"
	// FieldCollect holds the string denoting the collect field in the database.
	FieldCollect = "collect"
	// Table holds the table name of the subject in the database.
	Table = "subjects"
)

// Columns holds all SQL columns for subject fields.
var Columns = []string{
	FieldID,
	FieldImage,
	FieldSummary,
	FieldName,
	FieldDate,
	FieldNameCn,
	FieldOnHold,
	FieldWish,
	FieldDoing,
	FieldSubjectType,
	FieldCollect,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultImage holds the default value on creation for the "image" field.
	DefaultImage string
	// SummaryValidator is a validator for the "summary" field. It is called by the builders before save.
	SummaryValidator func(string) error
	// DefaultSubjectType holds the default value on creation for the "subject_type" field.
	DefaultSubjectType uint8
	// DefaultCollect holds the default value on creation for the "collect" field.
	DefaultCollect uint32
)

// OrderOption defines the ordering options for the Subject queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByImage orders the results by the image field.
func ByImage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImage, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDate orders the results by the date field.
func ByDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDate, opts...).ToFunc()
}

// ByNameCn orders the results by the name_cn field.
func ByNameCn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameCn, opts...).ToFunc()
}

// ByOnHold orders the results by the on_hold field.
func ByOnHold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOnHold, opts...).ToFunc()
}

// ByWish orders the results by the wish field.
func ByWish(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWish, opts...).ToFunc()
}

// ByDoing orders the results by the doing field.
func ByDoing(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDoing, opts...).ToFunc()
}

// BySubjectType orders the results by the subject_type field.
func BySubjectType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectType, opts...).ToFunc()
}

// ByCollect orders the results by the collect field.
func ByCollect(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCollect, opts...).ToFunc()
}
