// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Members is the predicate function for members builders.
type Members func(*sql.Selector)

// Subject is the predicate function for subject builders.
type Subject func(*sql.Selector)
