// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/collection"
	"backend/ent/members"
	"backend/ent/predicate"
	"backend/ent/subject"
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeCollection = "Collection"
	TypeMembers    = "Members"
	TypeSubject    = "Subject"
)

// CollectionMutation represents an operation that mutates the Collection nodes in the graph.
type CollectionMutation struct {
	config
	op            Op
	typ           string
	id            *int
	uid           *uint32
	adduid        *int32
	sub_id        *int
	addsub_id     *int
	_type         *uint8
	add_type      *int8
	if_comment    *bool
	comment       *string
	score         *int8
	addscore      *int8
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Collection, error)
	predicates    []predicate.Collection
}

var _ ent.Mutation = (*CollectionMutation)(nil)

// collectionOption allows management of the mutation configuration using functional options.
type collectionOption func(*CollectionMutation)

// newCollectionMutation creates new mutation for the Collection entity.
func newCollectionMutation(c config, op Op, opts ...collectionOption) *CollectionMutation {
	m := &CollectionMutation{
		config:        c,
		op:            op,
		typ:           TypeCollection,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withCollectionID sets the ID field of the mutation.
func withCollectionID(id int) collectionOption {
	return func(m *CollectionMutation) {
		var (
			err   error
			once  sync.Once
			value *Collection
		)
		m.oldValue = func(ctx context.Context) (*Collection, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Collection.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withCollection sets the old Collection of the mutation.
func withCollection(node *Collection) collectionOption {
	return func(m *CollectionMutation) {
		m.oldValue = func(context.Context) (*Collection, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m CollectionMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m CollectionMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *CollectionMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *CollectionMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Collection.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUID sets the "uid" field.
func (m *CollectionMutation) SetUID(u uint32) {
	m.uid = &u
	m.adduid = nil
}

// UID returns the value of the "uid" field in the mutation.
func (m *CollectionMutation) UID() (r uint32, exists bool) {
	v := m.uid
	if v == nil {
		return
	}
	return *v, true
}

// OldUID returns the old "uid" field's value of the Collection entity.
// If the Collection object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CollectionMutation) OldUID(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUID: %w", err)
	}
	return oldValue.UID, nil
}

// AddUID adds u to the "uid" field.
func (m *CollectionMutation) AddUID(u int32) {
	if m.adduid != nil {
		*m.adduid += u
	} else {
		m.adduid = &u
	}
}

// AddedUID returns the value that was added to the "uid" field in this mutation.
func (m *CollectionMutation) AddedUID() (r int32, exists bool) {
	v := m.adduid
	if v == nil {
		return
	}
	return *v, true
}

// ResetUID resets all changes to the "uid" field.
func (m *CollectionMutation) ResetUID() {
	m.uid = nil
	m.adduid = nil
}

// SetSubID sets the "sub_id" field.
func (m *CollectionMutation) SetSubID(i int) {
	m.sub_id = &i
	m.addsub_id = nil
}

// SubID returns the value of the "sub_id" field in the mutation.
func (m *CollectionMutation) SubID() (r int, exists bool) {
	v := m.sub_id
	if v == nil {
		return
	}
	return *v, true
}

// OldSubID returns the old "sub_id" field's value of the Collection entity.
// If the Collection object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CollectionMutation) OldSubID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSubID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSubID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSubID: %w", err)
	}
	return oldValue.SubID, nil
}

// AddSubID adds i to the "sub_id" field.
func (m *CollectionMutation) AddSubID(i int) {
	if m.addsub_id != nil {
		*m.addsub_id += i
	} else {
		m.addsub_id = &i
	}
}

// AddedSubID returns the value that was added to the "sub_id" field in this mutation.
func (m *CollectionMutation) AddedSubID() (r int, exists bool) {
	v := m.addsub_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetSubID resets all changes to the "sub_id" field.
func (m *CollectionMutation) ResetSubID() {
	m.sub_id = nil
	m.addsub_id = nil
}

// SetType sets the "type" field.
func (m *CollectionMutation) SetType(u uint8) {
	m._type = &u
	m.add_type = nil
}

// GetType returns the value of the "type" field in the mutation.
func (m *CollectionMutation) GetType() (r uint8, exists bool) {
	v := m._type
	if v == nil {
		return
	}
	return *v, true
}

// OldType returns the old "type" field's value of the Collection entity.
// If the Collection object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CollectionMutation) OldType(ctx context.Context) (v uint8, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldType: %w", err)
	}
	return oldValue.Type, nil
}

// AddType adds u to the "type" field.
func (m *CollectionMutation) AddType(u int8) {
	if m.add_type != nil {
		*m.add_type += u
	} else {
		m.add_type = &u
	}
}

// AddedType returns the value that was added to the "type" field in this mutation.
func (m *CollectionMutation) AddedType() (r int8, exists bool) {
	v := m.add_type
	if v == nil {
		return
	}
	return *v, true
}

// ResetType resets all changes to the "type" field.
func (m *CollectionMutation) ResetType() {
	m._type = nil
	m.add_type = nil
}

// SetIfComment sets the "if_comment" field.
func (m *CollectionMutation) SetIfComment(b bool) {
	m.if_comment = &b
}

// IfComment returns the value of the "if_comment" field in the mutation.
func (m *CollectionMutation) IfComment() (r bool, exists bool) {
	v := m.if_comment
	if v == nil {
		return
	}
	return *v, true
}

// OldIfComment returns the old "if_comment" field's value of the Collection entity.
// If the Collection object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CollectionMutation) OldIfComment(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIfComment is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIfComment requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIfComment: %w", err)
	}
	return oldValue.IfComment, nil
}

// ResetIfComment resets all changes to the "if_comment" field.
func (m *CollectionMutation) ResetIfComment() {
	m.if_comment = nil
}

// SetComment sets the "comment" field.
func (m *CollectionMutation) SetComment(s string) {
	m.comment = &s
}

// Comment returns the value of the "comment" field in the mutation.
func (m *CollectionMutation) Comment() (r string, exists bool) {
	v := m.comment
	if v == nil {
		return
	}
	return *v, true
}

// OldComment returns the old "comment" field's value of the Collection entity.
// If the Collection object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CollectionMutation) OldComment(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldComment is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldComment requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldComment: %w", err)
	}
	return oldValue.Comment, nil
}

// ResetComment resets all changes to the "comment" field.
func (m *CollectionMutation) ResetComment() {
	m.comment = nil
}

// SetScore sets the "score" field.
func (m *CollectionMutation) SetScore(i int8) {
	m.score = &i
	m.addscore = nil
}

// Score returns the value of the "score" field in the mutation.
func (m *CollectionMutation) Score() (r int8, exists bool) {
	v := m.score
	if v == nil {
		return
	}
	return *v, true
}

// OldScore returns the old "score" field's value of the Collection entity.
// If the Collection object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CollectionMutation) OldScore(ctx context.Context) (v int8, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldScore is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldScore requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldScore: %w", err)
	}
	return oldValue.Score, nil
}

// AddScore adds i to the "score" field.
func (m *CollectionMutation) AddScore(i int8) {
	if m.addscore != nil {
		*m.addscore += i
	} else {
		m.addscore = &i
	}
}

// AddedScore returns the value that was added to the "score" field in this mutation.
func (m *CollectionMutation) AddedScore() (r int8, exists bool) {
	v := m.addscore
	if v == nil {
		return
	}
	return *v, true
}

// ResetScore resets all changes to the "score" field.
func (m *CollectionMutation) ResetScore() {
	m.score = nil
	m.addscore = nil
}

// Where appends a list predicates to the CollectionMutation builder.
func (m *CollectionMutation) Where(ps ...predicate.Collection) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the CollectionMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *CollectionMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Collection, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *CollectionMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *CollectionMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Collection).
func (m *CollectionMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *CollectionMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.uid != nil {
		fields = append(fields, collection.FieldUID)
	}
	if m.sub_id != nil {
		fields = append(fields, collection.FieldSubID)
	}
	if m._type != nil {
		fields = append(fields, collection.FieldType)
	}
	if m.if_comment != nil {
		fields = append(fields, collection.FieldIfComment)
	}
	if m.comment != nil {
		fields = append(fields, collection.FieldComment)
	}
	if m.score != nil {
		fields = append(fields, collection.FieldScore)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *CollectionMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case collection.FieldUID:
		return m.UID()
	case collection.FieldSubID:
		return m.SubID()
	case collection.FieldType:
		return m.GetType()
	case collection.FieldIfComment:
		return m.IfComment()
	case collection.FieldComment:
		return m.Comment()
	case collection.FieldScore:
		return m.Score()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *CollectionMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case collection.FieldUID:
		return m.OldUID(ctx)
	case collection.FieldSubID:
		return m.OldSubID(ctx)
	case collection.FieldType:
		return m.OldType(ctx)
	case collection.FieldIfComment:
		return m.OldIfComment(ctx)
	case collection.FieldComment:
		return m.OldComment(ctx)
	case collection.FieldScore:
		return m.OldScore(ctx)
	}
	return nil, fmt.Errorf("unknown Collection field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CollectionMutation) SetField(name string, value ent.Value) error {
	switch name {
	case collection.FieldUID:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUID(v)
		return nil
	case collection.FieldSubID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSubID(v)
		return nil
	case collection.FieldType:
		v, ok := value.(uint8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetType(v)
		return nil
	case collection.FieldIfComment:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIfComment(v)
		return nil
	case collection.FieldComment:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetComment(v)
		return nil
	case collection.FieldScore:
		v, ok := value.(int8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetScore(v)
		return nil
	}
	return fmt.Errorf("unknown Collection field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *CollectionMutation) AddedFields() []string {
	var fields []string
	if m.adduid != nil {
		fields = append(fields, collection.FieldUID)
	}
	if m.addsub_id != nil {
		fields = append(fields, collection.FieldSubID)
	}
	if m.add_type != nil {
		fields = append(fields, collection.FieldType)
	}
	if m.addscore != nil {
		fields = append(fields, collection.FieldScore)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *CollectionMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case collection.FieldUID:
		return m.AddedUID()
	case collection.FieldSubID:
		return m.AddedSubID()
	case collection.FieldType:
		return m.AddedType()
	case collection.FieldScore:
		return m.AddedScore()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CollectionMutation) AddField(name string, value ent.Value) error {
	switch name {
	case collection.FieldUID:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUID(v)
		return nil
	case collection.FieldSubID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSubID(v)
		return nil
	case collection.FieldType:
		v, ok := value.(int8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddType(v)
		return nil
	case collection.FieldScore:
		v, ok := value.(int8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddScore(v)
		return nil
	}
	return fmt.Errorf("unknown Collection numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *CollectionMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *CollectionMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *CollectionMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Collection nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *CollectionMutation) ResetField(name string) error {
	switch name {
	case collection.FieldUID:
		m.ResetUID()
		return nil
	case collection.FieldSubID:
		m.ResetSubID()
		return nil
	case collection.FieldType:
		m.ResetType()
		return nil
	case collection.FieldIfComment:
		m.ResetIfComment()
		return nil
	case collection.FieldComment:
		m.ResetComment()
		return nil
	case collection.FieldScore:
		m.ResetScore()
		return nil
	}
	return fmt.Errorf("unknown Collection field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *CollectionMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *CollectionMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *CollectionMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *CollectionMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *CollectionMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *CollectionMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *CollectionMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Collection unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *CollectionMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Collection edge %s", name)
}

// MembersMutation represents an operation that mutates the Members nodes in the graph.
type MembersMutation struct {
	config
	op            Op
	typ           string
	id            *uint32
	username      *string
	email         *string
	password      *string
	nickname      *string
	avatar        *string
	gid           *uint8
	addgid        *int8
	register_time *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Members, error)
	predicates    []predicate.Members
}

var _ ent.Mutation = (*MembersMutation)(nil)

// membersOption allows management of the mutation configuration using functional options.
type membersOption func(*MembersMutation)

// newMembersMutation creates new mutation for the Members entity.
func newMembersMutation(c config, op Op, opts ...membersOption) *MembersMutation {
	m := &MembersMutation{
		config:        c,
		op:            op,
		typ:           TypeMembers,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withMembersID sets the ID field of the mutation.
func withMembersID(id uint32) membersOption {
	return func(m *MembersMutation) {
		var (
			err   error
			once  sync.Once
			value *Members
		)
		m.oldValue = func(ctx context.Context) (*Members, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Members.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withMembers sets the old Members of the mutation.
func withMembers(node *Members) membersOption {
	return func(m *MembersMutation) {
		m.oldValue = func(context.Context) (*Members, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m MembersMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m MembersMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Members entities.
func (m *MembersMutation) SetID(id uint32) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *MembersMutation) ID() (id uint32, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *MembersMutation) IDs(ctx context.Context) ([]uint32, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uint32{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Members.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUsername sets the "username" field.
func (m *MembersMutation) SetUsername(s string) {
	m.username = &s
}

// Username returns the value of the "username" field in the mutation.
func (m *MembersMutation) Username() (r string, exists bool) {
	v := m.username
	if v == nil {
		return
	}
	return *v, true
}

// OldUsername returns the old "username" field's value of the Members entity.
// If the Members object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MembersMutation) OldUsername(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUsername is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUsername requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUsername: %w", err)
	}
	return oldValue.Username, nil
}

// ResetUsername resets all changes to the "username" field.
func (m *MembersMutation) ResetUsername() {
	m.username = nil
}

// SetEmail sets the "email" field.
func (m *MembersMutation) SetEmail(s string) {
	m.email = &s
}

// Email returns the value of the "email" field in the mutation.
func (m *MembersMutation) Email() (r string, exists bool) {
	v := m.email
	if v == nil {
		return
	}
	return *v, true
}

// OldEmail returns the old "email" field's value of the Members entity.
// If the Members object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MembersMutation) OldEmail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEmail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmail: %w", err)
	}
	return oldValue.Email, nil
}

// ResetEmail resets all changes to the "email" field.
func (m *MembersMutation) ResetEmail() {
	m.email = nil
}

// SetPassword sets the "password" field.
func (m *MembersMutation) SetPassword(s string) {
	m.password = &s
}

// Password returns the value of the "password" field in the mutation.
func (m *MembersMutation) Password() (r string, exists bool) {
	v := m.password
	if v == nil {
		return
	}
	return *v, true
}

// OldPassword returns the old "password" field's value of the Members entity.
// If the Members object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MembersMutation) OldPassword(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPassword is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPassword requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPassword: %w", err)
	}
	return oldValue.Password, nil
}

// ResetPassword resets all changes to the "password" field.
func (m *MembersMutation) ResetPassword() {
	m.password = nil
}

// SetNickname sets the "nickname" field.
func (m *MembersMutation) SetNickname(s string) {
	m.nickname = &s
}

// Nickname returns the value of the "nickname" field in the mutation.
func (m *MembersMutation) Nickname() (r string, exists bool) {
	v := m.nickname
	if v == nil {
		return
	}
	return *v, true
}

// OldNickname returns the old "nickname" field's value of the Members entity.
// If the Members object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MembersMutation) OldNickname(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNickname is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNickname requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNickname: %w", err)
	}
	return oldValue.Nickname, nil
}

// ResetNickname resets all changes to the "nickname" field.
func (m *MembersMutation) ResetNickname() {
	m.nickname = nil
}

// SetAvatar sets the "avatar" field.
func (m *MembersMutation) SetAvatar(s string) {
	m.avatar = &s
}

// Avatar returns the value of the "avatar" field in the mutation.
func (m *MembersMutation) Avatar() (r string, exists bool) {
	v := m.avatar
	if v == nil {
		return
	}
	return *v, true
}

// OldAvatar returns the old "avatar" field's value of the Members entity.
// If the Members object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MembersMutation) OldAvatar(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAvatar is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAvatar requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAvatar: %w", err)
	}
	return oldValue.Avatar, nil
}

// ResetAvatar resets all changes to the "avatar" field.
func (m *MembersMutation) ResetAvatar() {
	m.avatar = nil
}

// SetGid sets the "gid" field.
func (m *MembersMutation) SetGid(u uint8) {
	m.gid = &u
	m.addgid = nil
}

// Gid returns the value of the "gid" field in the mutation.
func (m *MembersMutation) Gid() (r uint8, exists bool) {
	v := m.gid
	if v == nil {
		return
	}
	return *v, true
}

// OldGid returns the old "gid" field's value of the Members entity.
// If the Members object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MembersMutation) OldGid(ctx context.Context) (v uint8, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGid is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGid requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGid: %w", err)
	}
	return oldValue.Gid, nil
}

// AddGid adds u to the "gid" field.
func (m *MembersMutation) AddGid(u int8) {
	if m.addgid != nil {
		*m.addgid += u
	} else {
		m.addgid = &u
	}
}

// AddedGid returns the value that was added to the "gid" field in this mutation.
func (m *MembersMutation) AddedGid() (r int8, exists bool) {
	v := m.addgid
	if v == nil {
		return
	}
	return *v, true
}

// ResetGid resets all changes to the "gid" field.
func (m *MembersMutation) ResetGid() {
	m.gid = nil
	m.addgid = nil
}

// SetRegisterTime sets the "register_time" field.
func (m *MembersMutation) SetRegisterTime(s string) {
	m.register_time = &s
}

// RegisterTime returns the value of the "register_time" field in the mutation.
func (m *MembersMutation) RegisterTime() (r string, exists bool) {
	v := m.register_time
	if v == nil {
		return
	}
	return *v, true
}

// OldRegisterTime returns the old "register_time" field's value of the Members entity.
// If the Members object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MembersMutation) OldRegisterTime(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRegisterTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRegisterTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRegisterTime: %w", err)
	}
	return oldValue.RegisterTime, nil
}

// ResetRegisterTime resets all changes to the "register_time" field.
func (m *MembersMutation) ResetRegisterTime() {
	m.register_time = nil
}

// Where appends a list predicates to the MembersMutation builder.
func (m *MembersMutation) Where(ps ...predicate.Members) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the MembersMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *MembersMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Members, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *MembersMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *MembersMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Members).
func (m *MembersMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *MembersMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.username != nil {
		fields = append(fields, members.FieldUsername)
	}
	if m.email != nil {
		fields = append(fields, members.FieldEmail)
	}
	if m.password != nil {
		fields = append(fields, members.FieldPassword)
	}
	if m.nickname != nil {
		fields = append(fields, members.FieldNickname)
	}
	if m.avatar != nil {
		fields = append(fields, members.FieldAvatar)
	}
	if m.gid != nil {
		fields = append(fields, members.FieldGid)
	}
	if m.register_time != nil {
		fields = append(fields, members.FieldRegisterTime)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *MembersMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case members.FieldUsername:
		return m.Username()
	case members.FieldEmail:
		return m.Email()
	case members.FieldPassword:
		return m.Password()
	case members.FieldNickname:
		return m.Nickname()
	case members.FieldAvatar:
		return m.Avatar()
	case members.FieldGid:
		return m.Gid()
	case members.FieldRegisterTime:
		return m.RegisterTime()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *MembersMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case members.FieldUsername:
		return m.OldUsername(ctx)
	case members.FieldEmail:
		return m.OldEmail(ctx)
	case members.FieldPassword:
		return m.OldPassword(ctx)
	case members.FieldNickname:
		return m.OldNickname(ctx)
	case members.FieldAvatar:
		return m.OldAvatar(ctx)
	case members.FieldGid:
		return m.OldGid(ctx)
	case members.FieldRegisterTime:
		return m.OldRegisterTime(ctx)
	}
	return nil, fmt.Errorf("unknown Members field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MembersMutation) SetField(name string, value ent.Value) error {
	switch name {
	case members.FieldUsername:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUsername(v)
		return nil
	case members.FieldEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmail(v)
		return nil
	case members.FieldPassword:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPassword(v)
		return nil
	case members.FieldNickname:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNickname(v)
		return nil
	case members.FieldAvatar:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAvatar(v)
		return nil
	case members.FieldGid:
		v, ok := value.(uint8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGid(v)
		return nil
	case members.FieldRegisterTime:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRegisterTime(v)
		return nil
	}
	return fmt.Errorf("unknown Members field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *MembersMutation) AddedFields() []string {
	var fields []string
	if m.addgid != nil {
		fields = append(fields, members.FieldGid)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *MembersMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case members.FieldGid:
		return m.AddedGid()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MembersMutation) AddField(name string, value ent.Value) error {
	switch name {
	case members.FieldGid:
		v, ok := value.(int8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddGid(v)
		return nil
	}
	return fmt.Errorf("unknown Members numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *MembersMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *MembersMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *MembersMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Members nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *MembersMutation) ResetField(name string) error {
	switch name {
	case members.FieldUsername:
		m.ResetUsername()
		return nil
	case members.FieldEmail:
		m.ResetEmail()
		return nil
	case members.FieldPassword:
		m.ResetPassword()
		return nil
	case members.FieldNickname:
		m.ResetNickname()
		return nil
	case members.FieldAvatar:
		m.ResetAvatar()
		return nil
	case members.FieldGid:
		m.ResetGid()
		return nil
	case members.FieldRegisterTime:
		m.ResetRegisterTime()
		return nil
	}
	return fmt.Errorf("unknown Members field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *MembersMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *MembersMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *MembersMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *MembersMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *MembersMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *MembersMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *MembersMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Members unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *MembersMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Members edge %s", name)
}

// SubjectMutation represents an operation that mutates the Subject nodes in the graph.
type SubjectMutation struct {
	config
	op              Op
	typ             string
	id              *int
	image           *string
	summary         *string
	name            *string
	date            *string
	name_cn         *string
	on_hold         *uint32
	addon_hold      *int32
	wish            *uint32
	addwish         *int32
	doing           *uint32
	adddoing        *int32
	subject_type    *uint8
	addsubject_type *int8
	collect         *uint32
	addcollect      *int32
	drop            *uint32
	adddrop         *int32
	watched         *uint32
	addwatched      *int32
	clearedFields   map[string]struct{}
	done            bool
	oldValue        func(context.Context) (*Subject, error)
	predicates      []predicate.Subject
}

var _ ent.Mutation = (*SubjectMutation)(nil)

// subjectOption allows management of the mutation configuration using functional options.
type subjectOption func(*SubjectMutation)

// newSubjectMutation creates new mutation for the Subject entity.
func newSubjectMutation(c config, op Op, opts ...subjectOption) *SubjectMutation {
	m := &SubjectMutation{
		config:        c,
		op:            op,
		typ:           TypeSubject,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSubjectID sets the ID field of the mutation.
func withSubjectID(id int) subjectOption {
	return func(m *SubjectMutation) {
		var (
			err   error
			once  sync.Once
			value *Subject
		)
		m.oldValue = func(ctx context.Context) (*Subject, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Subject.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSubject sets the old Subject of the mutation.
func withSubject(node *Subject) subjectOption {
	return func(m *SubjectMutation) {
		m.oldValue = func(context.Context) (*Subject, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SubjectMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SubjectMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SubjectMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SubjectMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Subject.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetImage sets the "image" field.
func (m *SubjectMutation) SetImage(s string) {
	m.image = &s
}

// Image returns the value of the "image" field in the mutation.
func (m *SubjectMutation) Image() (r string, exists bool) {
	v := m.image
	if v == nil {
		return
	}
	return *v, true
}

// OldImage returns the old "image" field's value of the Subject entity.
// If the Subject object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SubjectMutation) OldImage(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldImage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldImage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldImage: %w", err)
	}
	return oldValue.Image, nil
}

// ResetImage resets all changes to the "image" field.
func (m *SubjectMutation) ResetImage() {
	m.image = nil
}

// SetSummary sets the "summary" field.
func (m *SubjectMutation) SetSummary(s string) {
	m.summary = &s
}

// Summary returns the value of the "summary" field in the mutation.
func (m *SubjectMutation) Summary() (r string, exists bool) {
	v := m.summary
	if v == nil {
		return
	}
	return *v, true
}

// OldSummary returns the old "summary" field's value of the Subject entity.
// If the Subject object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SubjectMutation) OldSummary(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSummary is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSummary requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSummary: %w", err)
	}
	return oldValue.Summary, nil
}

// ResetSummary resets all changes to the "summary" field.
func (m *SubjectMutation) ResetSummary() {
	m.summary = nil
}

// SetName sets the "name" field.
func (m *SubjectMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *SubjectMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Subject entity.
// If the Subject object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SubjectMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *SubjectMutation) ResetName() {
	m.name = nil
}

// SetDate sets the "date" field.
func (m *SubjectMutation) SetDate(s string) {
	m.date = &s
}

// Date returns the value of the "date" field in the mutation.
func (m *SubjectMutation) Date() (r string, exists bool) {
	v := m.date
	if v == nil {
		return
	}
	return *v, true
}

// OldDate returns the old "date" field's value of the Subject entity.
// If the Subject object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SubjectMutation) OldDate(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDate: %w", err)
	}
	return oldValue.Date, nil
}

// ResetDate resets all changes to the "date" field.
func (m *SubjectMutation) ResetDate() {
	m.date = nil
}

// SetNameCn sets the "name_cn" field.
func (m *SubjectMutation) SetNameCn(s string) {
	m.name_cn = &s
}

// NameCn returns the value of the "name_cn" field in the mutation.
func (m *SubjectMutation) NameCn() (r string, exists bool) {
	v := m.name_cn
	if v == nil {
		return
	}
	return *v, true
}

// OldNameCn returns the old "name_cn" field's value of the Subject entity.
// If the Subject object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SubjectMutation) OldNameCn(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNameCn is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNameCn requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNameCn: %w", err)
	}
	return oldValue.NameCn, nil
}

// ResetNameCn resets all changes to the "name_cn" field.
func (m *SubjectMutation) ResetNameCn() {
	m.name_cn = nil
}

// SetOnHold sets the "on_hold" field.
func (m *SubjectMutation) SetOnHold(u uint32) {
	m.on_hold = &u
	m.addon_hold = nil
}

// OnHold returns the value of the "on_hold" field in the mutation.
func (m *SubjectMutation) OnHold() (r uint32, exists bool) {
	v := m.on_hold
	if v == nil {
		return
	}
	return *v, true
}

// OldOnHold returns the old "on_hold" field's value of the Subject entity.
// If the Subject object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SubjectMutation) OldOnHold(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOnHold is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOnHold requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOnHold: %w", err)
	}
	return oldValue.OnHold, nil
}

// AddOnHold adds u to the "on_hold" field.
func (m *SubjectMutation) AddOnHold(u int32) {
	if m.addon_hold != nil {
		*m.addon_hold += u
	} else {
		m.addon_hold = &u
	}
}

// AddedOnHold returns the value that was added to the "on_hold" field in this mutation.
func (m *SubjectMutation) AddedOnHold() (r int32, exists bool) {
	v := m.addon_hold
	if v == nil {
		return
	}
	return *v, true
}

// ResetOnHold resets all changes to the "on_hold" field.
func (m *SubjectMutation) ResetOnHold() {
	m.on_hold = nil
	m.addon_hold = nil
}

// SetWish sets the "wish" field.
func (m *SubjectMutation) SetWish(u uint32) {
	m.wish = &u
	m.addwish = nil
}

// Wish returns the value of the "wish" field in the mutation.
func (m *SubjectMutation) Wish() (r uint32, exists bool) {
	v := m.wish
	if v == nil {
		return
	}
	return *v, true
}

// OldWish returns the old "wish" field's value of the Subject entity.
// If the Subject object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SubjectMutation) OldWish(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldWish is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldWish requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldWish: %w", err)
	}
	return oldValue.Wish, nil
}

// AddWish adds u to the "wish" field.
func (m *SubjectMutation) AddWish(u int32) {
	if m.addwish != nil {
		*m.addwish += u
	} else {
		m.addwish = &u
	}
}

// AddedWish returns the value that was added to the "wish" field in this mutation.
func (m *SubjectMutation) AddedWish() (r int32, exists bool) {
	v := m.addwish
	if v == nil {
		return
	}
	return *v, true
}

// ResetWish resets all changes to the "wish" field.
func (m *SubjectMutation) ResetWish() {
	m.wish = nil
	m.addwish = nil
}

// SetDoing sets the "doing" field.
func (m *SubjectMutation) SetDoing(u uint32) {
	m.doing = &u
	m.adddoing = nil
}

// Doing returns the value of the "doing" field in the mutation.
func (m *SubjectMutation) Doing() (r uint32, exists bool) {
	v := m.doing
	if v == nil {
		return
	}
	return *v, true
}

// OldDoing returns the old "doing" field's value of the Subject entity.
// If the Subject object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SubjectMutation) OldDoing(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDoing is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDoing requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDoing: %w", err)
	}
	return oldValue.Doing, nil
}

// AddDoing adds u to the "doing" field.
func (m *SubjectMutation) AddDoing(u int32) {
	if m.adddoing != nil {
		*m.adddoing += u
	} else {
		m.adddoing = &u
	}
}

// AddedDoing returns the value that was added to the "doing" field in this mutation.
func (m *SubjectMutation) AddedDoing() (r int32, exists bool) {
	v := m.adddoing
	if v == nil {
		return
	}
	return *v, true
}

// ResetDoing resets all changes to the "doing" field.
func (m *SubjectMutation) ResetDoing() {
	m.doing = nil
	m.adddoing = nil
}

// SetSubjectType sets the "subject_type" field.
func (m *SubjectMutation) SetSubjectType(u uint8) {
	m.subject_type = &u
	m.addsubject_type = nil
}

// SubjectType returns the value of the "subject_type" field in the mutation.
func (m *SubjectMutation) SubjectType() (r uint8, exists bool) {
	v := m.subject_type
	if v == nil {
		return
	}
	return *v, true
}

// OldSubjectType returns the old "subject_type" field's value of the Subject entity.
// If the Subject object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SubjectMutation) OldSubjectType(ctx context.Context) (v uint8, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSubjectType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSubjectType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSubjectType: %w", err)
	}
	return oldValue.SubjectType, nil
}

// AddSubjectType adds u to the "subject_type" field.
func (m *SubjectMutation) AddSubjectType(u int8) {
	if m.addsubject_type != nil {
		*m.addsubject_type += u
	} else {
		m.addsubject_type = &u
	}
}

// AddedSubjectType returns the value that was added to the "subject_type" field in this mutation.
func (m *SubjectMutation) AddedSubjectType() (r int8, exists bool) {
	v := m.addsubject_type
	if v == nil {
		return
	}
	return *v, true
}

// ResetSubjectType resets all changes to the "subject_type" field.
func (m *SubjectMutation) ResetSubjectType() {
	m.subject_type = nil
	m.addsubject_type = nil
}

// SetCollect sets the "collect" field.
func (m *SubjectMutation) SetCollect(u uint32) {
	m.collect = &u
	m.addcollect = nil
}

// Collect returns the value of the "collect" field in the mutation.
func (m *SubjectMutation) Collect() (r uint32, exists bool) {
	v := m.collect
	if v == nil {
		return
	}
	return *v, true
}

// OldCollect returns the old "collect" field's value of the Subject entity.
// If the Subject object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SubjectMutation) OldCollect(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCollect is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCollect requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCollect: %w", err)
	}
	return oldValue.Collect, nil
}

// AddCollect adds u to the "collect" field.
func (m *SubjectMutation) AddCollect(u int32) {
	if m.addcollect != nil {
		*m.addcollect += u
	} else {
		m.addcollect = &u
	}
}

// AddedCollect returns the value that was added to the "collect" field in this mutation.
func (m *SubjectMutation) AddedCollect() (r int32, exists bool) {
	v := m.addcollect
	if v == nil {
		return
	}
	return *v, true
}

// ResetCollect resets all changes to the "collect" field.
func (m *SubjectMutation) ResetCollect() {
	m.collect = nil
	m.addcollect = nil
}

// SetDrop sets the "drop" field.
func (m *SubjectMutation) SetDrop(u uint32) {
	m.drop = &u
	m.adddrop = nil
}

// Drop returns the value of the "drop" field in the mutation.
func (m *SubjectMutation) Drop() (r uint32, exists bool) {
	v := m.drop
	if v == nil {
		return
	}
	return *v, true
}

// OldDrop returns the old "drop" field's value of the Subject entity.
// If the Subject object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SubjectMutation) OldDrop(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDrop is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDrop requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDrop: %w", err)
	}
	return oldValue.Drop, nil
}

// AddDrop adds u to the "drop" field.
func (m *SubjectMutation) AddDrop(u int32) {
	if m.adddrop != nil {
		*m.adddrop += u
	} else {
		m.adddrop = &u
	}
}

// AddedDrop returns the value that was added to the "drop" field in this mutation.
func (m *SubjectMutation) AddedDrop() (r int32, exists bool) {
	v := m.adddrop
	if v == nil {
		return
	}
	return *v, true
}

// ResetDrop resets all changes to the "drop" field.
func (m *SubjectMutation) ResetDrop() {
	m.drop = nil
	m.adddrop = nil
}

// SetWatched sets the "watched" field.
func (m *SubjectMutation) SetWatched(u uint32) {
	m.watched = &u
	m.addwatched = nil
}

// Watched returns the value of the "watched" field in the mutation.
func (m *SubjectMutation) Watched() (r uint32, exists bool) {
	v := m.watched
	if v == nil {
		return
	}
	return *v, true
}

// OldWatched returns the old "watched" field's value of the Subject entity.
// If the Subject object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SubjectMutation) OldWatched(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldWatched is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldWatched requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldWatched: %w", err)
	}
	return oldValue.Watched, nil
}

// AddWatched adds u to the "watched" field.
func (m *SubjectMutation) AddWatched(u int32) {
	if m.addwatched != nil {
		*m.addwatched += u
	} else {
		m.addwatched = &u
	}
}

// AddedWatched returns the value that was added to the "watched" field in this mutation.
func (m *SubjectMutation) AddedWatched() (r int32, exists bool) {
	v := m.addwatched
	if v == nil {
		return
	}
	return *v, true
}

// ResetWatched resets all changes to the "watched" field.
func (m *SubjectMutation) ResetWatched() {
	m.watched = nil
	m.addwatched = nil
}

// Where appends a list predicates to the SubjectMutation builder.
func (m *SubjectMutation) Where(ps ...predicate.Subject) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SubjectMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SubjectMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Subject, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SubjectMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SubjectMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Subject).
func (m *SubjectMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SubjectMutation) Fields() []string {
	fields := make([]string, 0, 12)
	if m.image != nil {
		fields = append(fields, subject.FieldImage)
	}
	if m.summary != nil {
		fields = append(fields, subject.FieldSummary)
	}
	if m.name != nil {
		fields = append(fields, subject.FieldName)
	}
	if m.date != nil {
		fields = append(fields, subject.FieldDate)
	}
	if m.name_cn != nil {
		fields = append(fields, subject.FieldNameCn)
	}
	if m.on_hold != nil {
		fields = append(fields, subject.FieldOnHold)
	}
	if m.wish != nil {
		fields = append(fields, subject.FieldWish)
	}
	if m.doing != nil {
		fields = append(fields, subject.FieldDoing)
	}
	if m.subject_type != nil {
		fields = append(fields, subject.FieldSubjectType)
	}
	if m.collect != nil {
		fields = append(fields, subject.FieldCollect)
	}
	if m.drop != nil {
		fields = append(fields, subject.FieldDrop)
	}
	if m.watched != nil {
		fields = append(fields, subject.FieldWatched)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SubjectMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case subject.FieldImage:
		return m.Image()
	case subject.FieldSummary:
		return m.Summary()
	case subject.FieldName:
		return m.Name()
	case subject.FieldDate:
		return m.Date()
	case subject.FieldNameCn:
		return m.NameCn()
	case subject.FieldOnHold:
		return m.OnHold()
	case subject.FieldWish:
		return m.Wish()
	case subject.FieldDoing:
		return m.Doing()
	case subject.FieldSubjectType:
		return m.SubjectType()
	case subject.FieldCollect:
		return m.Collect()
	case subject.FieldDrop:
		return m.Drop()
	case subject.FieldWatched:
		return m.Watched()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SubjectMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case subject.FieldImage:
		return m.OldImage(ctx)
	case subject.FieldSummary:
		return m.OldSummary(ctx)
	case subject.FieldName:
		return m.OldName(ctx)
	case subject.FieldDate:
		return m.OldDate(ctx)
	case subject.FieldNameCn:
		return m.OldNameCn(ctx)
	case subject.FieldOnHold:
		return m.OldOnHold(ctx)
	case subject.FieldWish:
		return m.OldWish(ctx)
	case subject.FieldDoing:
		return m.OldDoing(ctx)
	case subject.FieldSubjectType:
		return m.OldSubjectType(ctx)
	case subject.FieldCollect:
		return m.OldCollect(ctx)
	case subject.FieldDrop:
		return m.OldDrop(ctx)
	case subject.FieldWatched:
		return m.OldWatched(ctx)
	}
	return nil, fmt.Errorf("unknown Subject field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SubjectMutation) SetField(name string, value ent.Value) error {
	switch name {
	case subject.FieldImage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetImage(v)
		return nil
	case subject.FieldSummary:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSummary(v)
		return nil
	case subject.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case subject.FieldDate:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDate(v)
		return nil
	case subject.FieldNameCn:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNameCn(v)
		return nil
	case subject.FieldOnHold:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOnHold(v)
		return nil
	case subject.FieldWish:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetWish(v)
		return nil
	case subject.FieldDoing:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDoing(v)
		return nil
	case subject.FieldSubjectType:
		v, ok := value.(uint8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSubjectType(v)
		return nil
	case subject.FieldCollect:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCollect(v)
		return nil
	case subject.FieldDrop:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDrop(v)
		return nil
	case subject.FieldWatched:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetWatched(v)
		return nil
	}
	return fmt.Errorf("unknown Subject field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SubjectMutation) AddedFields() []string {
	var fields []string
	if m.addon_hold != nil {
		fields = append(fields, subject.FieldOnHold)
	}
	if m.addwish != nil {
		fields = append(fields, subject.FieldWish)
	}
	if m.adddoing != nil {
		fields = append(fields, subject.FieldDoing)
	}
	if m.addsubject_type != nil {
		fields = append(fields, subject.FieldSubjectType)
	}
	if m.addcollect != nil {
		fields = append(fields, subject.FieldCollect)
	}
	if m.adddrop != nil {
		fields = append(fields, subject.FieldDrop)
	}
	if m.addwatched != nil {
		fields = append(fields, subject.FieldWatched)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SubjectMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case subject.FieldOnHold:
		return m.AddedOnHold()
	case subject.FieldWish:
		return m.AddedWish()
	case subject.FieldDoing:
		return m.AddedDoing()
	case subject.FieldSubjectType:
		return m.AddedSubjectType()
	case subject.FieldCollect:
		return m.AddedCollect()
	case subject.FieldDrop:
		return m.AddedDrop()
	case subject.FieldWatched:
		return m.AddedWatched()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SubjectMutation) AddField(name string, value ent.Value) error {
	switch name {
	case subject.FieldOnHold:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddOnHold(v)
		return nil
	case subject.FieldWish:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddWish(v)
		return nil
	case subject.FieldDoing:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDoing(v)
		return nil
	case subject.FieldSubjectType:
		v, ok := value.(int8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSubjectType(v)
		return nil
	case subject.FieldCollect:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCollect(v)
		return nil
	case subject.FieldDrop:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDrop(v)
		return nil
	case subject.FieldWatched:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddWatched(v)
		return nil
	}
	return fmt.Errorf("unknown Subject numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SubjectMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SubjectMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SubjectMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Subject nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SubjectMutation) ResetField(name string) error {
	switch name {
	case subject.FieldImage:
		m.ResetImage()
		return nil
	case subject.FieldSummary:
		m.ResetSummary()
		return nil
	case subject.FieldName:
		m.ResetName()
		return nil
	case subject.FieldDate:
		m.ResetDate()
		return nil
	case subject.FieldNameCn:
		m.ResetNameCn()
		return nil
	case subject.FieldOnHold:
		m.ResetOnHold()
		return nil
	case subject.FieldWish:
		m.ResetWish()
		return nil
	case subject.FieldDoing:
		m.ResetDoing()
		return nil
	case subject.FieldSubjectType:
		m.ResetSubjectType()
		return nil
	case subject.FieldCollect:
		m.ResetCollect()
		return nil
	case subject.FieldDrop:
		m.ResetDrop()
		return nil
	case subject.FieldWatched:
		m.ResetWatched()
		return nil
	}
	return fmt.Errorf("unknown Subject field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SubjectMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SubjectMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SubjectMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SubjectMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SubjectMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SubjectMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SubjectMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Subject unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SubjectMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Subject edge %s", name)
}
