// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/members"
	"backend/ent/predicate"
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeMembers = "Members"
)

// MembersMutation represents an operation that mutates the Members nodes in the graph.
type MembersMutation struct {
	config
	op            Op
	typ           string
	id            *uint32
	username      *string
	email         *string
	password      *string
	nickname      *string
	avatar        *string
	gid           *uint8
	addgid        *int8
	register_time *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Members, error)
	predicates    []predicate.Members
}

var _ ent.Mutation = (*MembersMutation)(nil)

// membersOption allows management of the mutation configuration using functional options.
type membersOption func(*MembersMutation)

// newMembersMutation creates new mutation for the Members entity.
func newMembersMutation(c config, op Op, opts ...membersOption) *MembersMutation {
	m := &MembersMutation{
		config:        c,
		op:            op,
		typ:           TypeMembers,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withMembersID sets the ID field of the mutation.
func withMembersID(id uint32) membersOption {
	return func(m *MembersMutation) {
		var (
			err   error
			once  sync.Once
			value *Members
		)
		m.oldValue = func(ctx context.Context) (*Members, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Members.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withMembers sets the old Members of the mutation.
func withMembers(node *Members) membersOption {
	return func(m *MembersMutation) {
		m.oldValue = func(context.Context) (*Members, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m MembersMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m MembersMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Members entities.
func (m *MembersMutation) SetID(id uint32) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *MembersMutation) ID() (id uint32, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *MembersMutation) IDs(ctx context.Context) ([]uint32, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uint32{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Members.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUsername sets the "username" field.
func (m *MembersMutation) SetUsername(s string) {
	m.username = &s
}

// Username returns the value of the "username" field in the mutation.
func (m *MembersMutation) Username() (r string, exists bool) {
	v := m.username
	if v == nil {
		return
	}
	return *v, true
}

// OldUsername returns the old "username" field's value of the Members entity.
// If the Members object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MembersMutation) OldUsername(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUsername is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUsername requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUsername: %w", err)
	}
	return oldValue.Username, nil
}

// ResetUsername resets all changes to the "username" field.
func (m *MembersMutation) ResetUsername() {
	m.username = nil
}

// SetEmail sets the "email" field.
func (m *MembersMutation) SetEmail(s string) {
	m.email = &s
}

// Email returns the value of the "email" field in the mutation.
func (m *MembersMutation) Email() (r string, exists bool) {
	v := m.email
	if v == nil {
		return
	}
	return *v, true
}

// OldEmail returns the old "email" field's value of the Members entity.
// If the Members object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MembersMutation) OldEmail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEmail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmail: %w", err)
	}
	return oldValue.Email, nil
}

// ResetEmail resets all changes to the "email" field.
func (m *MembersMutation) ResetEmail() {
	m.email = nil
}

// SetPassword sets the "password" field.
func (m *MembersMutation) SetPassword(s string) {
	m.password = &s
}

// Password returns the value of the "password" field in the mutation.
func (m *MembersMutation) Password() (r string, exists bool) {
	v := m.password
	if v == nil {
		return
	}
	return *v, true
}

// OldPassword returns the old "password" field's value of the Members entity.
// If the Members object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MembersMutation) OldPassword(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPassword is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPassword requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPassword: %w", err)
	}
	return oldValue.Password, nil
}

// ResetPassword resets all changes to the "password" field.
func (m *MembersMutation) ResetPassword() {
	m.password = nil
}

// SetNickname sets the "nickname" field.
func (m *MembersMutation) SetNickname(s string) {
	m.nickname = &s
}

// Nickname returns the value of the "nickname" field in the mutation.
func (m *MembersMutation) Nickname() (r string, exists bool) {
	v := m.nickname
	if v == nil {
		return
	}
	return *v, true
}

// OldNickname returns the old "nickname" field's value of the Members entity.
// If the Members object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MembersMutation) OldNickname(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNickname is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNickname requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNickname: %w", err)
	}
	return oldValue.Nickname, nil
}

// ResetNickname resets all changes to the "nickname" field.
func (m *MembersMutation) ResetNickname() {
	m.nickname = nil
}

// SetAvatar sets the "avatar" field.
func (m *MembersMutation) SetAvatar(s string) {
	m.avatar = &s
}

// Avatar returns the value of the "avatar" field in the mutation.
func (m *MembersMutation) Avatar() (r string, exists bool) {
	v := m.avatar
	if v == nil {
		return
	}
	return *v, true
}

// OldAvatar returns the old "avatar" field's value of the Members entity.
// If the Members object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MembersMutation) OldAvatar(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAvatar is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAvatar requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAvatar: %w", err)
	}
	return oldValue.Avatar, nil
}

// ResetAvatar resets all changes to the "avatar" field.
func (m *MembersMutation) ResetAvatar() {
	m.avatar = nil
}

// SetGid sets the "gid" field.
func (m *MembersMutation) SetGid(u uint8) {
	m.gid = &u
	m.addgid = nil
}

// Gid returns the value of the "gid" field in the mutation.
func (m *MembersMutation) Gid() (r uint8, exists bool) {
	v := m.gid
	if v == nil {
		return
	}
	return *v, true
}

// OldGid returns the old "gid" field's value of the Members entity.
// If the Members object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MembersMutation) OldGid(ctx context.Context) (v uint8, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGid is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGid requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGid: %w", err)
	}
	return oldValue.Gid, nil
}

// AddGid adds u to the "gid" field.
func (m *MembersMutation) AddGid(u int8) {
	if m.addgid != nil {
		*m.addgid += u
	} else {
		m.addgid = &u
	}
}

// AddedGid returns the value that was added to the "gid" field in this mutation.
func (m *MembersMutation) AddedGid() (r int8, exists bool) {
	v := m.addgid
	if v == nil {
		return
	}
	return *v, true
}

// ResetGid resets all changes to the "gid" field.
func (m *MembersMutation) ResetGid() {
	m.gid = nil
	m.addgid = nil
}

// SetRegisterTime sets the "register_time" field.
func (m *MembersMutation) SetRegisterTime(s string) {
	m.register_time = &s
}

// RegisterTime returns the value of the "register_time" field in the mutation.
func (m *MembersMutation) RegisterTime() (r string, exists bool) {
	v := m.register_time
	if v == nil {
		return
	}
	return *v, true
}

// OldRegisterTime returns the old "register_time" field's value of the Members entity.
// If the Members object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MembersMutation) OldRegisterTime(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRegisterTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRegisterTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRegisterTime: %w", err)
	}
	return oldValue.RegisterTime, nil
}

// ResetRegisterTime resets all changes to the "register_time" field.
func (m *MembersMutation) ResetRegisterTime() {
	m.register_time = nil
}

// Where appends a list predicates to the MembersMutation builder.
func (m *MembersMutation) Where(ps ...predicate.Members) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the MembersMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *MembersMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Members, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *MembersMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *MembersMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Members).
func (m *MembersMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *MembersMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.username != nil {
		fields = append(fields, members.FieldUsername)
	}
	if m.email != nil {
		fields = append(fields, members.FieldEmail)
	}
	if m.password != nil {
		fields = append(fields, members.FieldPassword)
	}
	if m.nickname != nil {
		fields = append(fields, members.FieldNickname)
	}
	if m.avatar != nil {
		fields = append(fields, members.FieldAvatar)
	}
	if m.gid != nil {
		fields = append(fields, members.FieldGid)
	}
	if m.register_time != nil {
		fields = append(fields, members.FieldRegisterTime)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *MembersMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case members.FieldUsername:
		return m.Username()
	case members.FieldEmail:
		return m.Email()
	case members.FieldPassword:
		return m.Password()
	case members.FieldNickname:
		return m.Nickname()
	case members.FieldAvatar:
		return m.Avatar()
	case members.FieldGid:
		return m.Gid()
	case members.FieldRegisterTime:
		return m.RegisterTime()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *MembersMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case members.FieldUsername:
		return m.OldUsername(ctx)
	case members.FieldEmail:
		return m.OldEmail(ctx)
	case members.FieldPassword:
		return m.OldPassword(ctx)
	case members.FieldNickname:
		return m.OldNickname(ctx)
	case members.FieldAvatar:
		return m.OldAvatar(ctx)
	case members.FieldGid:
		return m.OldGid(ctx)
	case members.FieldRegisterTime:
		return m.OldRegisterTime(ctx)
	}
	return nil, fmt.Errorf("unknown Members field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MembersMutation) SetField(name string, value ent.Value) error {
	switch name {
	case members.FieldUsername:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUsername(v)
		return nil
	case members.FieldEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmail(v)
		return nil
	case members.FieldPassword:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPassword(v)
		return nil
	case members.FieldNickname:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNickname(v)
		return nil
	case members.FieldAvatar:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAvatar(v)
		return nil
	case members.FieldGid:
		v, ok := value.(uint8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGid(v)
		return nil
	case members.FieldRegisterTime:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRegisterTime(v)
		return nil
	}
	return fmt.Errorf("unknown Members field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *MembersMutation) AddedFields() []string {
	var fields []string
	if m.addgid != nil {
		fields = append(fields, members.FieldGid)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *MembersMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case members.FieldGid:
		return m.AddedGid()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MembersMutation) AddField(name string, value ent.Value) error {
	switch name {
	case members.FieldGid:
		v, ok := value.(int8)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddGid(v)
		return nil
	}
	return fmt.Errorf("unknown Members numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *MembersMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *MembersMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *MembersMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Members nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *MembersMutation) ResetField(name string) error {
	switch name {
	case members.FieldUsername:
		m.ResetUsername()
		return nil
	case members.FieldEmail:
		m.ResetEmail()
		return nil
	case members.FieldPassword:
		m.ResetPassword()
		return nil
	case members.FieldNickname:
		m.ResetNickname()
		return nil
	case members.FieldAvatar:
		m.ResetAvatar()
		return nil
	case members.FieldGid:
		m.ResetGid()
		return nil
	case members.FieldRegisterTime:
		m.ResetRegisterTime()
		return nil
	}
	return fmt.Errorf("unknown Members field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *MembersMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *MembersMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *MembersMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *MembersMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *MembersMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *MembersMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *MembersMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Members unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *MembersMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Members edge %s", name)
}
