// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/members"
	"backend/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	membersFields := schema.Members{}.Fields()
	_ = membersFields
	// membersDescUsername is the schema descriptor for username field.
	membersDescUsername := membersFields[1].Descriptor()
	// members.DefaultUsername holds the default value on creation for the username field.
	members.DefaultUsername = membersDescUsername.Default.(string)
	// members.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	members.UsernameValidator = membersDescUsername.Validators[0].(func(string) error)
	// membersDescNickname is the schema descriptor for nickname field.
	membersDescNickname := membersFields[2].Descriptor()
	// members.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	members.NicknameValidator = membersDescNickname.Validators[0].(func(string) error)
	// membersDescAvatar is the schema descriptor for avatar field.
	membersDescAvatar := membersFields[3].Descriptor()
	// members.AvatarValidator is a validator for the "avatar" field. It is called by the builders before save.
	members.AvatarValidator = membersDescAvatar.Validators[0].(func(string) error)
	// membersDescGid is the schema descriptor for gid field.
	membersDescGid := membersFields[4].Descriptor()
	// members.DefaultGid holds the default value on creation for the gid field.
	members.DefaultGid = membersDescGid.Default.(uint8)
}
