// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/:member_id/member/comment": {
            "get": {
                "description": "Get Comments By Uid",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "member_id",
                        "name": "member_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "comments",
                        "schema": {
                            "$ref": "#/definitions/response.CommentsResp"
                        }
                    }
                }
            }
        },
        "/:subject_id/subject/comment": {
            "get": {
                "description": "Get Comments By Id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "subject_id",
                        "name": "subject_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "comments",
                        "schema": {
                            "$ref": "#/definitions/response.CommentsResp"
                        }
                    }
                }
            }
        },
        "/:type/collection": {
            "get": {
                "description": "Get Comments By type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "type",
                        "name": "type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "collections",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ent.Collection"
                            }
                        }
                    }
                }
            }
        },
        "/cancel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cancel",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/collection/:subject_id": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get Subject by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "parameters": [
                    {
                        "description": "collection",
                        "name": "collection",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/collection.AddOrUpdateCollectionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "UpdateCollection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "parameters": [
                    {
                        "description": "collection",
                        "name": "collection",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/collection.AddOrUpdateCollectionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "parameters": [
                    {
                        "description": "login req",
                        "name": "loginReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserLoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": " login success ",
                        "schema": {
                            "$ref": "#/definitions/response.UserLoginResp"
                        }
                    }
                }
            }
        },
        "/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get Me",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "responses": {
                    "200": {
                        "description": "MemberInfo",
                        "schema": {
                            "$ref": "#/definitions/response.UserGetResp"
                        }
                    }
                }
            }
        },
        "/modify": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "ModifyInfo",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "parameters": [
                    {
                        "description": "Modify Info",
                        "name": "ModifyReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ModifyInfoReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Register",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "parameters": [
                    {
                        "description": "register req",
                        "name": "registerReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserRegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": " register success "
                    }
                }
            }
        },
        "/subject/:subject_id": {
            "get": {
                "description": "Get Subject by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subject"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "subject_id",
                        "name": "subject_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SubjectInfo",
                        "schema": {
                            "$ref": "#/definitions/response.GetSubjectWithFieldResp"
                        }
                    }
                }
            }
        },
        "/subject/create": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create Subject",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subject"
                ],
                "parameters": [
                    {
                        "description": "SubjectCreate",
                        "name": "SubjectReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/subject.CreateSubjectWithSaveReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/subject/get": {
            "get": {
                "description": "Get All Subject",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subject"
                ],
                "responses": {
                    "200": {
                        "description": "SubjectsInfo",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.GetSubjectResp"
                            }
                        }
                    }
                }
            }
        },
        "/user/:id/avatar": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get Avatar",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "MemberAvatar",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/:member_id": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "GetMember",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "member_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "MemberInfo",
                        "schema": {
                            "$ref": "#/definitions/response.UserGetResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "collection.AddOrUpdateCollectionReq": {
            "type": "object",
            "required": [
                "has_comment",
                "type"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                },
                "ep_status": {
                    "type": "integer"
                },
                "has_comment": {
                    "type": "boolean"
                },
                "score": {
                    "type": "integer"
                },
                "type": {
                    "maximum": 5,
                    "minimum": 1,
                    "allOf": [
                        {
                            "$ref": "#/definitions/collection.CollectionType"
                        }
                    ]
                }
            }
        },
        "collection.CollectionType": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4,
                5
            ],
            "x-enum-varnames": [
                "Wish",
                "Watched",
                "Doing",
                "OnHold",
                "Dropped"
            ]
        },
        "ent.Collection": {
            "type": "object",
            "properties": {
                "add_time": {
                    "description": "AddTime holds the value of the \"add_time\" field.",
                    "type": "string"
                },
                "comment": {
                    "description": "Comment holds the value of the \"comment\" field.",
                    "type": "string"
                },
                "edges": {
                    "description": "Edges holds the relations/edges for other nodes in the graph.\nThe values are being populated by the CollectionQuery when eager-loading is set.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/ent.CollectionEdges"
                        }
                    ]
                },
                "ep_status": {
                    "description": "EpStatus holds the value of the \"ep_status\" field.",
                    "type": "integer"
                },
                "has_comment": {
                    "description": "HasComment holds the value of the \"has_comment\" field.",
                    "type": "boolean"
                },
                "id": {
                    "description": "ID of the ent.",
                    "type": "integer"
                },
                "member_id": {
                    "description": "MemberID holds the value of the \"member_id\" field.",
                    "type": "integer"
                },
                "score": {
                    "description": "Score holds the value of the \"score\" field.",
                    "type": "integer"
                },
                "subject_id": {
                    "description": "SubjectID holds the value of the \"subject_id\" field.",
                    "type": "integer"
                },
                "type": {
                    "description": "Type holds the value of the \"type\" field.",
                    "type": "integer"
                }
            }
        },
        "ent.CollectionEdges": {
            "type": "object",
            "properties": {
                "member": {
                    "description": "Member holds the value of the member edge.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/ent.Members"
                        }
                    ]
                },
                "subject": {
                    "description": "Subject holds the value of the subject edge.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/ent.Subject"
                        }
                    ]
                }
            }
        },
        "ent.Members": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "Avatar holds the value of the \"avatar\" field.",
                    "type": "string"
                },
                "edges": {
                    "description": "Edges holds the relations/edges for other nodes in the graph.\nThe values are being populated by the MembersQuery when eager-loading is set.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/ent.MembersEdges"
                        }
                    ]
                },
                "email": {
                    "description": "Email holds the value of the \"email\" field.",
                    "type": "string"
                },
                "gid": {
                    "description": "Gid holds the value of the \"gid\" field.",
                    "type": "integer"
                },
                "id": {
                    "description": "ID of the ent.",
                    "type": "integer"
                },
                "nickname": {
                    "description": "Nickname holds the value of the \"nickname\" field.",
                    "type": "string"
                },
                "password": {
                    "description": "Password holds the value of the \"password\" field.",
                    "type": "string"
                },
                "register_time": {
                    "description": "RegisterTime holds the value of the \"register_time\" field.",
                    "type": "string"
                },
                "username": {
                    "description": "Username holds the value of the \"username\" field.",
                    "type": "string"
                }
            }
        },
        "ent.MembersEdges": {
            "type": "object",
            "properties": {
                "collections": {
                    "description": "Collections holds the value of the collections edge.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ent.Collection"
                    }
                }
            }
        },
        "ent.Subject": {
            "type": "object",
            "properties": {
                "doing": {
                    "description": "Doing holds the value of the \"doing\" field.",
                    "type": "integer"
                },
                "dropped": {
                    "description": "Dropped holds the value of the \"dropped\" field.",
                    "type": "integer"
                },
                "edges": {
                    "description": "Edges holds the relations/edges for other nodes in the graph.\nThe values are being populated by the SubjectQuery when eager-loading is set.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/ent.SubjectEdges"
                        }
                    ]
                },
                "episodes": {
                    "description": "Episodes holds the value of the \"episodes\" field.",
                    "type": "integer"
                },
                "id": {
                    "description": "ID of the ent.",
                    "type": "integer"
                },
                "image": {
                    "description": "Image holds the value of the \"image\" field.",
                    "type": "string"
                },
                "name": {
                    "description": "Name holds the value of the \"name\" field.",
                    "type": "string"
                },
                "name_cn": {
                    "description": "NameCn holds the value of the \"name_cn\" field.",
                    "type": "string"
                },
                "on_hold": {
                    "description": "OnHold holds the value of the \"on_hold\" field.",
                    "type": "integer"
                },
                "summary": {
                    "description": "Summary holds the value of the \"summary\" field.",
                    "type": "string"
                },
                "watched": {
                    "description": "Watched holds the value of the \"watched\" field.",
                    "type": "integer"
                },
                "wish": {
                    "description": "Wish holds the value of the \"wish\" field.",
                    "type": "integer"
                }
            }
        },
        "ent.SubjectEdges": {
            "type": "object",
            "properties": {
                "collections": {
                    "description": "Collections holds the value of the collections edge.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ent.Collection"
                    }
                },
                "subject_field": {
                    "description": "SubjectField holds the value of the subject_field edge.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/ent.SubjectField"
                        }
                    ]
                }
            }
        },
        "ent.SubjectField": {
            "type": "object",
            "properties": {
                "average_score": {
                    "description": "AverageScore holds the value of the \"average_score\" field.",
                    "type": "number"
                },
                "date": {
                    "description": "Date holds the value of the \"date\" field.",
                    "type": "integer"
                },
                "edges": {
                    "description": "Edges holds the relations/edges for other nodes in the graph.\nThe values are being populated by the SubjectFieldQuery when eager-loading is set.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/ent.SubjectFieldEdges"
                        }
                    ]
                },
                "id": {
                    "description": "ID of the ent.",
                    "type": "integer"
                },
                "month": {
                    "description": "Month holds the value of the \"month\" field.",
                    "type": "integer"
                },
                "rank": {
                    "description": "Rank holds the value of the \"rank\" field.",
                    "type": "integer"
                },
                "rate_1": {
                    "description": "Rate1 holds the value of the \"rate_1\" field.",
                    "type": "integer"
                },
                "rate_10": {
                    "description": "Rate10 holds the value of the \"rate_10\" field.",
                    "type": "integer"
                },
                "rate_2": {
                    "description": "Rate2 holds the value of the \"rate_2\" field.",
                    "type": "integer"
                },
                "rate_3": {
                    "description": "Rate3 holds the value of the \"rate_3\" field.",
                    "type": "integer"
                },
                "rate_4": {
                    "description": "Rate4 holds the value of the \"rate_4\" field.",
                    "type": "integer"
                },
                "rate_5": {
                    "description": "Rate5 holds the value of the \"rate_5\" field.",
                    "type": "integer"
                },
                "rate_6": {
                    "description": "Rate6 holds the value of the \"rate_6\" field.",
                    "type": "integer"
                },
                "rate_7": {
                    "description": "Rate7 holds the value of the \"rate_7\" field.",
                    "type": "integer"
                },
                "rate_8": {
                    "description": "Rate8 holds the value of the \"rate_8\" field.",
                    "type": "integer"
                },
                "rate_9": {
                    "description": "Rate9 holds the value of the \"rate_9\" field.",
                    "type": "integer"
                },
                "weekday": {
                    "description": "Weekday holds the value of the \"weekday\" field.",
                    "type": "integer"
                },
                "year": {
                    "description": "Year holds the value of the \"year\" field.",
                    "type": "integer"
                }
            }
        },
        "ent.SubjectFieldEdges": {
            "type": "object",
            "properties": {
                "subject": {
                    "description": "Subject holds the value of the subject edge.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/ent.Subject"
                        }
                    ]
                }
            }
        },
        "response.CommentResp": {
            "type": "object",
            "properties": {
                "Comment": {
                    "type": "string"
                },
                "MemberID": {
                    "type": "integer"
                },
                "SubjectId": {
                    "type": "integer"
                },
                "Time": {
                    "type": "string"
                },
                "Type": {
                    "$ref": "#/definitions/collection.CollectionType"
                }
            }
        },
        "response.CommentsResp": {
            "type": "object",
            "properties": {
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.CommentResp"
                    }
                }
            }
        },
        "response.GetSubjectResp": {
            "type": "object",
            "properties": {
                "info": {
                    "$ref": "#/definitions/subject.Model"
                }
            }
        },
        "response.GetSubjectWithFieldResp": {
            "type": "object",
            "properties": {
                "field": {
                    "$ref": "#/definitions/subjectField.Model"
                },
                "info": {
                    "$ref": "#/definitions/subject.Model"
                }
            }
        },
        "response.UserGetResp": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "Avatar holds the value of the \"avatar\" field.",
                    "type": "string"
                },
                "email": {
                    "description": "Email holds the value of the \"email\" field.",
                    "type": "string"
                },
                "gid": {
                    "description": "Gid holds the value of the \"gid\" field.",
                    "type": "integer"
                },
                "nickname": {
                    "description": "Nickname holds the value of the \"nickname\" field.",
                    "type": "string"
                },
                "register_time": {
                    "description": "RegisterTime holds the value of the \"register_time\" field.",
                    "type": "string"
                },
                "uid": {
                    "description": "ID of the ent.",
                    "type": "integer"
                },
                "username": {
                    "description": "Username holds the value of the \"username\" field.",
                    "type": "string"
                }
            }
        },
        "response.UserLoginResp": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "subject.CreateSubjectReq": {
            "type": "object",
            "required": [
                "date",
                "episodes",
                "month",
                "name",
                "name_cn",
                "summary",
                "weekDay",
                "year"
            ],
            "properties": {
                "date": {
                    "type": "integer",
                    "maximum": 31,
                    "minimum": 1
                },
                "episodes": {
                    "type": "integer"
                },
                "image": {
                    "description": "subject",
                    "type": "string"
                },
                "month": {
                    "type": "integer",
                    "maximum": 12,
                    "minimum": 1
                },
                "name": {
                    "type": "string"
                },
                "name_cn": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "weekDay": {
                    "type": "integer",
                    "maximum": 7,
                    "minimum": 1
                },
                "year": {
                    "description": "subject field",
                    "type": "integer"
                }
            }
        },
        "subject.CreateSubjectWithSaveReq": {
            "type": "object",
            "required": [
                "createSubject"
            ],
            "properties": {
                "createSubject": {
                    "description": "subject",
                    "allOf": [
                        {
                            "$ref": "#/definitions/subject.CreateSubjectReq"
                        }
                    ]
                }
            }
        },
        "subject.Model": {
            "type": "object",
            "properties": {
                "doing": {
                    "type": "integer"
                },
                "dropped": {
                    "type": "integer"
                },
                "episodes": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "name_cn": {
                    "type": "string"
                },
                "on_hold": {
                    "type": "integer"
                },
                "summary": {
                    "type": "string"
                },
                "watched": {
                    "type": "integer"
                },
                "wish": {
                    "type": "integer"
                }
            }
        },
        "subjectField.Model": {
            "type": "object",
            "properties": {
                "average_score": {
                    "type": "number"
                },
                "date": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "month": {
                    "type": "integer"
                },
                "rank": {
                    "type": "integer"
                },
                "rate_1": {
                    "type": "integer"
                },
                "rate_10": {
                    "type": "integer"
                },
                "rate_2": {
                    "type": "integer"
                },
                "rate_3": {
                    "type": "integer"
                },
                "rate_4": {
                    "type": "integer"
                },
                "rate_5": {
                    "type": "integer"
                },
                "rate_6": {
                    "type": "integer"
                },
                "rate_7": {
                    "type": "integer"
                },
                "rate_8": {
                    "type": "integer"
                },
                "rate_9": {
                    "type": "integer"
                },
                "weekday": {
                    "type": "integer"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "user.Info": {
            "type": "object",
            "required": [
                "email",
                "nickname",
                "username"
            ],
            "properties": {
                "email": {
                    "description": "Email holds the value of the \"email\" field.",
                    "type": "string"
                },
                "nickname": {
                    "description": "Nickname holds the value of the \"nickname\" field.",
                    "type": "string"
                },
                "password": {
                    "description": "Password holds the value of the \"password\" field.",
                    "type": "string"
                },
                "username": {
                    "description": "Username holds the value of the \"username\" field.",
                    "type": "string"
                }
            }
        },
        "user.ModifyInfoReq": {
            "type": "object",
            "required": [
                "info"
            ],
            "properties": {
                "info": {
                    "$ref": "#/definitions/user.Info"
                }
            }
        },
        "user.UserLoginReq": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "user.UserRegisterReq": {
            "type": "object",
            "required": [
                "email",
                "nickname",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "This is a sample server Petstore server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
