definitions:
  collection.AddOrUpdateCollectionReq:
    properties:
      comment:
        type: string
      ep_status:
        type: integer
      has_comment:
        type: boolean
      score:
        type: integer
      type:
        allOf:
        - $ref: '#/definitions/collection.CollectionType'
        maximum: 5
        minimum: 1
    required:
    - has_comment
    - type
    type: object
  collection.CollectionType:
    enum:
    - 1
    - 2
    - 3
    - 4
    - 5
    type: integer
    x-enum-varnames:
    - Wish
    - Watched
    - Doing
    - OnHold
    - Dropped
  response.CommentResp:
    properties:
      Comment:
        type: string
      MemberID:
        type: integer
      SubjectId:
        type: integer
      Time:
        type: string
    type: object
  response.CommentsResp:
    properties:
      comments:
        items:
          $ref: '#/definitions/response.CommentResp'
        type: array
    type: object
  response.GetSubjectResp:
    properties:
      date:
        type: string
      doing:
        type: integer
      dropped:
        type: integer
      id:
        type: integer
      image:
        type: string
      name:
        type: string
      name_cn:
        type: string
      on_hold:
        type: integer
      subject_type:
        type: integer
      summary:
        type: string
      watched:
        type: integer
      wish:
        type: integer
    type: object
  response.UserGetResp:
    properties:
      avatar:
        description: Avatar holds the value of the "avatar" field.
        type: string
      email:
        description: Email holds the value of the "email" field.
        type: string
      gid:
        description: Gid holds the value of the "gid" field.
        type: integer
      nickname:
        description: Nickname holds the value of the "nickname" field.
        type: string
      register_time:
        description: RegisterTime holds the value of the "register_time" field.
        type: string
      uid:
        description: ID of the ent.
        type: integer
      username:
        description: Username holds the value of the "username" field.
        type: string
    type: object
  response.UserLoginResp:
    properties:
      token:
        type: string
    type: object
  subject.CreateSubjectReq:
    properties:
      date:
        maximum: 31
        minimum: 1
        type: integer
      episodes:
        type: integer
      image:
        description: subject
        type: string
      month:
        maximum: 12
        minimum: 1
        type: integer
      name:
        type: string
      name_cn:
        type: string
      summary:
        type: string
      weekDay:
        maximum: 7
        minimum: 1
        type: integer
      year:
        description: subject field
        type: integer
    required:
    - date
    - episodes
    - month
    - name
    - name_cn
    - summary
    - weekDay
    - year
    type: object
  user.Info:
    properties:
      email:
        description: Email holds the value of the "email" field.
        type: string
      nickname:
        description: Nickname holds the value of the "nickname" field.
        type: string
      password:
        description: Password holds the value of the "password" field.
        type: string
      username:
        description: Username holds the value of the "username" field.
        type: string
    required:
    - email
    - nickname
    - password
    - username
    type: object
  user.ModifyInfoReq:
    properties:
      info:
        $ref: '#/definitions/user.Info'
    required:
    - info
    type: object
  user.UserLoginReq:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  user.UserRegisterReq:
    properties:
      email:
        type: string
      nickname:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - nickname
    - password
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /:member_id/member/comment:
    get:
      consumes:
      - application/json
      description: Get Comments By Uid
      parameters:
      - description: member_id
        in: path
        name: member_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: comments
          schema:
            $ref: '#/definitions/response.CommentsResp'
      tags:
      - Collection
  /:subject_id/subject/comment:
    get:
      consumes:
      - application/json
      description: Get Comments By Id
      parameters:
      - description: subject_id
        in: path
        name: subject_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: comments
          schema:
            $ref: '#/definitions/response.CommentsResp'
      tags:
      - Collection
  /cancel:
    post:
      consumes:
      - application/json
      description: Cancel
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      tags:
      - Member
  /collection/:subject_id:
    patch:
      consumes:
      - application/json
      description: UpdateCollection
      parameters:
      - description: collection
        in: body
        name: collection
        required: true
        schema:
          $ref: '#/definitions/collection.AddOrUpdateCollectionReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      tags:
      - Collection
    post:
      consumes:
      - application/json
      description: Get Subject by id
      parameters:
      - description: collection
        in: body
        name: collection
        required: true
        schema:
          $ref: '#/definitions/collection.AddOrUpdateCollectionReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      tags:
      - Collection
  /login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: login req
        in: body
        name: loginReq
        required: true
        schema:
          $ref: '#/definitions/user.UserLoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: ' login success '
          schema:
            $ref: '#/definitions/response.UserLoginResp'
      tags:
      - Member
  /me:
    get:
      consumes:
      - application/json
      description: Get Me
      produces:
      - application/json
      responses:
        "200":
          description: MemberInfo
          schema:
            $ref: '#/definitions/response.UserGetResp'
      security:
      - BearerAuth: []
      tags:
      - Member
  /modify:
    put:
      consumes:
      - multipart/form-data
      description: ModifyInfo
      parameters:
      - description: Modify Info
        in: body
        name: ModifyReq
        required: true
        schema:
          $ref: '#/definitions/user.ModifyInfoReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      tags:
      - Member
  /register:
    post:
      consumes:
      - application/json
      description: Register
      parameters:
      - description: register req
        in: body
        name: registerReq
        required: true
        schema:
          $ref: '#/definitions/user.UserRegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: ' register success '
      tags:
      - Member
  /subject/:subject_id:
    get:
      consumes:
      - application/json
      description: Get Subject by id
      parameters:
      - description: subject_id
        in: path
        name: subject_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: SubjectInfo
          schema:
            $ref: '#/definitions/response.GetSubjectResp'
      tags:
      - Subject
  /subject/create:
    post:
      consumes:
      - application/json
      description: Create Subject
      parameters:
      - description: SubjectCreate
        in: body
        name: SubjectReq
        required: true
        schema:
          $ref: '#/definitions/subject.CreateSubjectReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      tags:
      - Subject
  /subject/get:
    get:
      consumes:
      - application/json
      description: Get All Subject
      produces:
      - application/json
      responses:
        "200":
          description: SubjectsInfo
          schema:
            items:
              $ref: '#/definitions/response.GetSubjectResp'
            type: array
      tags:
      - Subject
  /user/:id/avatar:
    get:
      consumes:
      - application/json
      description: Get Avatar
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: MemberAvatar
          schema:
            type: string
      security:
      - BearerAuth: []
      tags:
      - Member
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
